version: '3.0'

services:
  front-end-app:
    build: ./app-front-end
    container_name: "front-end-app"
    ports:
      - "80:80"
    depends_on:
      - back-end-app
      - mongo
      - redis

  back-end-app:
    build: ./App_BackEnd
    container_name: "back-end-app"
    environment:
      - PORT = 5000
      - HOST_MONGO = 'mongodb://mongo/pokedex'
      - HOST_REDIS = 'redis'
      - PORT_REDIS = 6379
    ports:
      - "5000:5000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  redis:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always