apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: appback
    role: control
    tier: backend  
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: appback
    role: control
    tier: backend 
