apiVersion: v1
kind: ReplicationController
metadata:
  name: back-controller
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: appback
    role: back-client
    tier: backend
spec:
  replicas: 1
  # Pod Template
  template:
    metadata:
      labels:
        app: appback
        role: back-client
        tier: backend
    spec:
      containers:
      - name: back-end-app
        # Uncomment this line to use the public docker hub image
        image: javiss1254/back-end-app
        resources:
          # The resources specification for each Pod, more details here:
          # http://kubernetes.io/v1.1/docs/design/resources.html#resource-specifications
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "5000" 
        - name: HOST_MONGO
          value: "mongodb://javisolares:Chimchar004@ds125198.mlab.com:25198/pokedex"
        - name: HOST_REDIS
          value: "redis"
        - name: PORT_REDIS
          value: "6379"
        ports:
          # More details on the container ports here,
          # http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html#_v1_containerport
          # The port exposed by the container
        - containerPort: 5000