apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: appback
    role: back-client
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: appback
    role: back-client
    tier: backend