apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-controller
  labels:
    app: appfront
    role: front
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appfront
        role: front
        tier: frontend
    spec:
      containers:
      - name: front-end-app
        image: javiss1254/front-end-app
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80